version: '3.9'

services:

  # gobuild:
  #   build: .
  #   container_name: 'go'
  #   ports: 
  #     - 8080:8080
  #   volumes: 
  #     - ./:/app
  #   working_dir: /app
  #   depends_on: 
  #     - postgresql
  #     - postgresql_test
  
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: postgresql
    working_dir: /app
    restart: always
    environment: 
      POSTGRES_DB: 'reddit'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes: 
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data
    
  postgresql_test:
    image: postgres:latest
    ports:
      - 5433:5432
    container_name: postgresql_test
    working_dir: /app
    restart: always
    environment: 
      POSTGRES_DB: 'reddit_test'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes: 
      - dump_test:/app/dump
      - postgresql_test:/var/lib/postgresql/data

          
volumes: 
  dump:
  postgresql:
  dump_test:
  postgresql_test: