bind_addr = ":8080" 
log_level = "debug"
database_url = "postgresql://user:password@localhost:5432/reddit?sslmode=disable"
#database_url = "host=localhost dbname=reddit sslmode=disable user=user password=password"
session_key = "some_secret_key"
token_ttl = "120h"